### ISSUE TITLE
Running with Resnet50

### ISSUE THREAD

**Issue by purn3ndu** [dwyatte/tensorflow-serving-benchmark#1]
Hi, Can the server create_model.py be used to run resnet50?

**Comment by dwyatte** [comment]
Sure, you will just need to edit `inputs` and `outputs` in create_model.py to point to the corresponding ResNet-50 tensors. 

This should just add a large constant to the timings as the benchmark is simply meant measure the latency of the TensorFlow Serving components (gRPC server, serialization/deserialization, injection into the graph).

**Comment by purn3ndu** [comment]
Thanks Dean,

I used your benchmarking part of the code for testing a tf serving implementation of resnet.

https://github.com/purnendu91/serving/blob/master/tensorflow_serving/example/resnet_client.py

https://github.com/purnendu91/serving/blob/master/tensorflow_serving/example/resnet_saved_model.py

:)

**Comment by dwyatte** [comment]
Great, hope the code was helpful. Closing this issue.
